name: Deploy React app to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install
        npm install gh-pages --save-dev

    - name: Set up Git user
      run: |
        git config --global user.name "Yunitula"
        git config --global user.email "yunishjt@gmail.com"
        # Configure Git to use the token for HTTPS GitHub authentication
        git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com".insteadOf "https://github.com"

    - name: Build the app
      run: npm run build

    - name: Deploy to GitHub Pages
      run: |
        npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pass the token to the deployment step
